version: '3'

services:
  web:
    container_name: app_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    container_name: app_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  db_test:
    container_name: app_db_test
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_test_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
    db_data:
    db_test_data:
